PlusOneBuy/FBPlusOneBuy/Controllers/ChartController.cs
using FBPlusOneBuy.DBModels;
using FBPlusOneBuy.Repositories;
using FBPlusOneBuy.Services;
using FBPlusOneBuy.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FBPlusOneBuy.Controllers
{
    public class ChartController : Controller
    {
        [HttpPost]
        public ActionResult GroupOrderDetailChart(int GroupOrderID)
        {
            var name = new List<string>();
            var qty = new List<int>();
            var dateTime = new List<string>();
            var price = new List<decimal>(); 
            var arrayData = new { name,dateTime, qty, price };
            
            var GOdetailService = new GroupOrderDetailService();
            var data = GOdetailService.GetDetailByGroupOrderID(GroupOrderID);
            foreach (var item in data)
            {
                name.Add(item.Name);
                qty.Add(item.Quantity);
                dateTime.Add(item.MessageDateTime.ToString());
                var amount = item.Quantity * item.UnitPrice;
                price.Add(amount);
            }           
            return Json(arrayData);
        }

        [HttpPost]
        public ActionResult GroupOrderChart(int CampaignID)
        {
            var name = new List<string>();
            var qty = new List<int>();
            var dateTime = new List<string>();
            var price = new List<decimal>();
            var arrayData = new { name, dateTime, qty, price };

            var GOdetailService = new GroupOrderDetailService();
            var data = GOdetailService.GetDetailByCampaignID(CampaignID);
            foreach (var item in data)
            {
                name.Add(item.Name);
                qty.Add(item.Quantity);
                dateTime.Add(item.MessageDateTime.ToString());
                var amount = item.Quantity * item.UnitPrice;
                price.Add(amount);
            }
            return Json(arrayData);
        }
        [HttpPost]
        public ActionResult FbOrderChart(int liveId)
        {
            LivePostsRepository livePost_repo = new LivePostsRepository();
            var time = livePost_repo.GetLivePost(liveId);

            OrderRepositories order_repo = new OrderRepositories();
            var orders = order_repo.GetOrders(liveId);

            var post = time.postTime.Minute;
            TimeSpan interval = time.endTime - time.postTime;
            var minutes = Math.Round(Convert.ToDouble(interval.TotalMinutes));
            var intervalOrders = new List<CommentOrderLIstViewModel>();

            var sum = new List<int>();
            var datetime = new List<string>();
            var chartData = new { datetime, sum };
            for (var i = 0; i <= minutes; i++)
            {
                intervalOrders = orders.Where((x) => post+i <=x.OrderDateTime.Minute  && x.OrderDateTime.Minute < post + i+1).ToList();

                var qty = 0;
                foreach (var item in intervalOrders)
                {
                    qty += item.Quantity;
                }
                datetime.Add(time.postTime.AddMinutes(i).ToString("HH:mm"));
                sum.Add(qty);
            }

            return Json(chartData);
        }

        [HttpPost]
        public ActionResult ReCordViewers(string livePageID, string numberOfViewers)
        {
            try
            {
                int liveID = LivePostService.Select(livePageID);
                ViewerService viewerService = new ViewerService();
                viewerService.Create(liveID, numberOfViewers);
                return Json("OK",JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json("error:" + e, JsonRequestBehavior.AllowGet);
            }
            
        }
        [HttpGet]
        public ActionResult GetViewers(int liveID)
        {
            try
            {
                Viewer viewer = new Viewer();
                ViewerService viewerService = new ViewerService();
                viewer = viewerService.SearchViewerByLiveID(liveID);
                return Json(viewer.NumberOfViewers, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

PlusOneBuy/FBPlusOneBuy/Controllers/listController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FBPlusOneBuy.Repositories;
using FBPlusOneBuy.Services;
using Newtonsoft.Json;
using FBPlusOneBuy.Models;
using FBPlusOneBuy.ViewModels;
using Microsoft.AspNet.Identity;
using FBPlusOneBuy.DBModels;

namespace FBPlusOneBuy.Controllers
{
    [Authorize]
    public class listController : Controller
    {
        [HttpGet]
        // GET: list
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string livePageID, string liveName, string keywordPattern)
        {
            string userid = User.Identity.GetUserId();
            //string fanpageid = (string)Session["FanPageID"];
            int fanpageid = FanPageService.GetPageId(userid);
            //新增直播進資料庫
            LivePostService.CreateLivePost(livePageID, liveName, fanpageid);
            //新增商品進資料庫
            ProductRepositories product_repo = new ProductRepositories();
            var products = ProductService.GetCurrentProducts().ProductItems;
            foreach (var item in products)
            {
                if (!product_repo.SelectProduct(item.SkuId))
                {
                    product_repo.InsertProduct(item);
                }
            }
            ViewData["products"] = products;
            ViewData["livePageID"] = livePageID;
            ViewData["keywordPattern"] = keywordPattern;
            return View();
        }

        [HttpPost]
        public ActionResult GetPlusOneBuyOrders(string livePageID, string keywordPattern)
        {
            //try
            //{
            //string token = Session["token"].ToString();
            string userid = User.Identity.GetUserId();
            string token = FanPageService.GetToken(userid);
            var products = ProductService.GetCurrentProducts().ProductItems;
            var OrderList = CommentFilterService.getNewOrderList(livePageID, token, products, keywordPattern);
            var Success_order = new List<OrderList>();
            if (OrderList.Count > 0)
            {
                var order_repo = new OrderRepositories();
                Session["lastPostTime"] = OrderList.Last().OrderDateTime;
                foreach (var order in OrderList)
                {
                    //留言成功，數量修改
                    if (ProductService.UpdateProductQty(order.Product.SkuId,order.Quantity))
                    {
                        Success_order.Add(order);
                        order_repo.InsertOrder(order);
                        FBSendMsgService.SuccessOrderToSendMsg(livePageID, order, token);
                    }
                    else  //留言失敗
                    {
                        FBSendMsgService.FailedOrderToSendMsg(livePageID, order, token);
                    }
                }
            }
            var result = JsonConvert.SerializeObject(Success_order);
            return Json(result);
            //}
            //catch (Exception e)
            //{
            //    DateTime date = DateTime.UtcNow.AddHours(8);
            //    string today = date.ToString("yyyy-MM-dd");
            //    string now = date.ToString("yyyy-MM-dd HH:mm:ss");
            //    if (!Directory.Exists("C:\\log"))
            //    {
            //        Directory.CreateDirectory("C:\\log\\");
            //    }

            //    string nowPath = "C:\\log\\" + today + ".txt";

            //    System.IO.File.AppendAllText("C:\\log\\" + today + ".txt", "\r\n" + now + " : " + e);

            //    return Json("error");
            //}
        }
        [HttpPost]
        public ActionResult SetPostEndtime(string livePageID)
        {
            OrderRepositories o_repo = new OrderRepositories();
            decimal Amount = o_repo.GetAmount(livePageID);
            int QtyOfOrders = o_repo.GetQtyOfOrders(livePageID);
            var live_repo = new LivePostsRepository();
            int views = 0;
            if (Session["views"] != null)
            {
                views = (int)Session["views"];

            }
            live_repo.UpdatePost(livePageID, QtyOfOrders, Amount, DateTime.UtcNow.AddHours(8), views);
            Session.Abandon();
            return RedirectToAction("Index", "Report");
        }

        [HttpPost]
        public void SendMsgByButton(string livePageID)
        {
            var live_repo = new LivePostsRepository();
            int liveid = live_repo.Select(livePageID);
            var order_repo = new OrderRepositories();
            //List<string> ids = new List<string> { "3032519476788720", "2762673820474754" };
            List<MsgTextViewModel> ordersinfo = order_repo.SelectAllOrdersInfo(liveid);
            //string token = (string)Session["token"];
            string userid = User.Identity.GetUserId();
            string token = FanPageService.GetToken(userid);
            var orders = new List<OrderList>();
            foreach (var orderinfo in ordersinfo)
            {
                var order = new OrderList();
                order.CustomerID = orderinfo.CustomerID;
                order.CustomerName = orderinfo.CustomerName;
                order.OrderID = orderinfo.OrderID;
                order.Product = new ProductViewModel { Salepage_id = orderinfo.ProductPageID, SkuId = orderinfo.ProductID, ProductName = orderinfo.ProductName };
                order.Quantity = orderinfo.Quantity;
                orders.Add(order);
                FBSendMsgService.SuccessOrderToSendMsg(livePageID, order, token);
            }
        }
        [HttpGet]
        public ActionResult GetROIOrderInfo(string livePageId)
        {
            OrderRepositories o_repo = new OrderRepositories();
            var amount = o_repo.GetAmount(livePageId);
            var qty = o_repo.GetQtyOfOrders(livePageId);
            var Order = new { Amount = amount, Qty = qty };
            return Json(Order, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetLiveVideoViews(string livePageID)
        {
            Session["views"] = null;
            string userid = User.Identity.GetUserId();
            try
            {
                //string token = Session["token"].ToString();

                string token = FanPageService.GetToken(userid);
                int views = FBRequestService.GetLiveVideoViews(livePageID, token);
                if (Session["views"] == null)
                {
                    Session["views"] = views;
                }
                else
                {
                    if ((int)Session["views"] < views)
                    {
                        Session["views"] = views;
                    }
                }

                return Json(views, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return Json(0, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpGet]
        public ActionResult GetOrdersCount(string livePageID)
        {
            int ordersCount = 0;
            OrderService orderService = new OrderService();
            List<Order> orders = orderService.GetOrders(livePageID);
            DateTime dtNow = DateTime.UtcNow.AddHours(8);
             
            if (Session["lastCountTime"] == null)
            {
                ordersCount = orders.Count;
                if (ordersCount!=0)
                {
                    Session["lastCountTime"] = orders.Last().OrderDateTime;
                }                
            }
            else
            {
                DateTime lastCountTime = (DateTime)Session["lastCountTime"];
                ordersCount = orders.Where(x=>DateTime.Compare(x.OrderDateTime, lastCountTime) >0).Count();
                Session["lastCountTime"] = orders.Last().OrderDateTime;
            }

            return Json(ordersCount, JsonRequestBehavior.AllowGet);
        }
    }
}

PlusOneBuy/FBPlusOneBuy/Views/list/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Main_Layout.cshtml";
    List<FBPlusOneBuy.ViewModels.ProductViewModel> products = ViewData["products"] as List<FBPlusOneBuy.ViewModels.ProductViewModel>;
}
<div class="container bg-light shadow ">
    <div class="row p-3 ">
        <div class="col-2">
            <div class="card listcard border-secondary shadow">
                <div class="row no-gutters align-items-center">
                    <div class="col m-3">
                        <div class="text-md font-weight-bold text-primary text-uppercase mb-1">觀看人數</div>
                        <div class="h3 mb-0 font-weight-bold text-gray" id="views">0</div>
                    </div>
                    <div class="col-auto m-2">
                        <i class="fas fa-eye fa-2x "></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="card listcard border-primary shadow">
                <div class="row no-gutters align-items-center">
                    <div class="col m-3">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">收單數量</div>
                        <div class="h3 mb-0 font-weight-bold text-gray" id="num">
                            0
                        </div>
                    </div>
                    <div class="col-auto m-2">
                        <i class="fas fa-users fa-2x "></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="card listcard border-warning shadow">
                <div class="row no-gutters align-items-center">
                    <div class="col m-3">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">收單金額</div>
                        <div class="h3 mb-0 font-weight-bold text-gray" id="money">0</div>
                    </div>
                    <div class="col-auto m-2">
                        <i class="fas fa-dollar-sign fa-2x "></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="card listcard border-success shadow">
                <div class="row no-gutters align-items-center">
                    <div class="col m-3">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">成交數量</div>
                        <div class="h3 mb-0 font-weight-bold text-gray" id="Ordernum">0</div>
                    </div>
                    <div class="col-auto m-2">
                        <div><i class="fas fa-sort-amount-up fa-2x"></i></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-2 ">
            <div class="card listcard border-danger shadow">
                <div class="row no-gutters align-items-center">
                    <div class="col m-3">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">成交金額</div>
                        <div class="h3 mb-0 font-weight-bold " id="Ordermoney">0</div>
                    </div>
                    <div class="col-auto m-2">
                        <i class="fas fa-coins fa-2x text-gray"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row mt-3">
        <div class="col-8"></div>
        <div class="col">
            <button id="btn_sentMsg" class="btn btn-primary ">寄送購物車連結</button>
        </div>
        <div class="col">
            <form id="EndPost" method="post" action="/list/SetPostEndtime">
                <input name="livePageID" value="@ViewData["livePageID"]" type="hidden" />
                <button type="button" id="btn_endpost" class="btn btn-dark ">結束本次推播</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            <h3>直播商品</h3>
            <table class="table" style="font-size:14px;">
                <thead>
                    <tr>
                        <th>名稱</th>
                        <th>規格</th>
                        <th>關鍵字</th>
                        <th>價格</th>
                        <th>數量</th>
                        <th>可售</th>
                    </tr>
                </thead>
                <tbody>
                    @if (products != null)
                    {
                        for (int i = 0; i < products.Count; i++)
                        {
                            <tr id="s_@products[i].SkuId">
                                <td>@products[i].ProductName</td>
                                <td>@products[i].SkuName</td>
                                <td>@products[i].Keyword</td>
                                <td>@String.Format("{0:N0}", products[i].UnitPrice)</td>
                                <td>@products[i].Qty</td>
                                <td>@products[i].PresetQty</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <canvas id="chartjs-0" style="width:80%"></canvas>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"> <h3>留言清單</h3></div>
                <div class="col">
                    <span>留言關鍵字:@ViewData["keywordPattern"]</span>
                </div>
                <div class="col-12">
                    <table id="ListTable" class="table table-hover">
                        <thead>
                            <tr>
                                <th>顧客名稱</th>
                                <th>關鍵字</th>
                                <th>商品名稱</th>
                                <th>數量</th>
                                <th>留言時間</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
                
            </div>
        </div>
        
    </div>   

</div>
<div style="width:50%;">
    <canvas id="chartjs-0"></canvas>
</div>

    @*<canvas id="chartjs-0" class="chartjs" width="150" height="150"
            style="display: block; height: 200px; width: 150px;"></canvas>*@


@section EndJS
{
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    <script>
        $(document).ready(function () {            
            GetData();           
            $("#btn_sentMsg").click(sendMsg);
            setInterval(DrawOrdersCountLine, 5000);
            
        function sendMsg() {
            $.ajax({
                type: "POST",
                url: '@Url.Action("SendMsgByButton", "list")',
                data: { livePageID: '@ViewData["livePageID"]' }
            }).done(function(response) {
                console.log(response);
            });
        }
        });
        var countSeconds = 0;
        var num = 0;
        var money = 0;
        var myChart=new Chart(document.getElementById("chartjs-0"),
            {
                "type": "line",
                "data": {
                    "labels": [],
                    "datasets": [{
                        "label": "留言訂單數量",
                        "data": [],
                        "fill": false,
                        "borderColor": "rgb(75, 192, 192)",
                        "lineTension": 0.1
                    },{
                        "label": "觀看人數",
                        "data": [],
                        "fill": false,
                        "borderColor": "rgb(157, 156, 255)",
                        "lineTension": 0.1
                        }
                    ]
                },
                "options": {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                stepSize: 1,
                                

                            }
                        }]
                    }
                }
            });
        function GetData() {
            $.ajax({
                type: 'post',
                url: '/list/GetPlusOneBuyOrders',
                data: { livePageID:'@ViewData["livePageID"]',keywordPattern:'@ViewData["keywordPattern"]'},
                dataType: "json",
                cache: false,
                success: function (Result) {
                    var json = JSON.parse(Result);

                    for (var i = 0; i < json.length; i++) {
                        var Time = json[i].OrderDateTime
                        var newDate = Time.substring(0,10)+ " " +Time.substring(11,19);
                        $('#ListTable').append("<tr><td>" + json[i].CustomerName + "</td>" +
                            "<td>" + json[i].Keyword + "</td>" +
                            "<td>" + json[i].Product.ProductName + "</td>" +
                            "<td>" + json[i].Quantity + "</td>" +
                            "<td>" + newDate + "</td></tr>");
                        money = json[i].Product.UnitPrice;
                    }
                },
                error: function () {
                    alert("error");
                }
            }).then(function () {
                setTimeout(GetLiveVideoViews, 5000);
                setTimeout(GetData, 3000);
                setTimeout(GetROIOrderInfo, 3000);
                setTimeout(GetQty, 3000);
                
            })
        }

        function GetROIOrderInfo() {
            $.ajax({
                type: "GET",
                    url: '@Url.Action("GetROIOrderInfo", "list")',
                    data: {livePageId:'@ViewData["livePageID"]'}
            }).done(function (order) {
                $('#num').text(order.Qty)
                $('#money').text(order.Amount)

                if (order.Qty > 4) {
                     $('#Ordernum').text(3)
                     $('#Ordermoney').text(3*money)
                }
                if (order.Qty > 2) {
                     $('#Ordernum').text(1)
                     $('#Ordermoney').text(1*money)
                }

                });
        }
        function GetLiveVideoViews() {
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetLiveVideoViews","list")',
                data: { livePageID: '@ViewData["livePageID"]' }
            }).done(function(views) {
                $('#views').text(views);

                myChart.data.datasets[1].data.push(views);
                myChart.update();
            });
        }
        function GetQty() {
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetPresetQty","Product")'
            }).done(function(result) {
                if (result != "") {
                    for (var i = 0; i < result.length; i++) {
                        var ID = '#s_' + result[i].ID + ' td:nth-child(6)'
                        $(ID).text(result[i].PresetQty)
                        if (result[i].PresetQty == 0) {
                            $(ID).addClass("text-danger")
                        }
                    }
                }
            });
        }
        function DrawOrdersCountLine() {
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetOrdersCount","List")',
                data: { livePageID: '@ViewData["livePageID"]' }
            }).done(function(response) {
                countSeconds = countSeconds + 5;
                //if (+response > myChart.options.scales.yAxes[0].ticks.max)
                //{
                //    myChart.options.scales.yAxes[0].ticks.max = response;
                //}
                myChart.data.labels.push(countSeconds + "秒");
                myChart.data.datasets[0].data.push(response);
                myChart.update();

            });
        }

        $("#btn_endpost").on('click',
            function (e) {
                e.preventDefault();
                var data = JSON.stringify(myChart.data.datasets[1].data);
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("ReCordViewers","Chart")',
                    data: { livePageID : "@ViewData["livePageID"]", numberOfViewers: data }
                }).done(function(response) {
                    console.log(response);
                    $("#EndPost").submit();
                });
            });
    </script>
}