PlusOneBuy/FBPlusOneBuy/Controllers/ReportController.cs
using FBPlusOneBuy.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FBPlusOneBuy.Repositories;
using FBPlusOneBuy.ViewModels;
using Microsoft.AspNet.Identity;

namespace FBPlusOneBuy.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            LivePostsRepository livePost_repo = new LivePostsRepository();
            ViewData.Model = livePost_repo.GetAllLivePosts();
            return View();
        }
        public ActionResult FbList()
        {
            LivePostsRepository livePost_repo = new LivePostsRepository();
            ViewData.Model = livePost_repo.GetAllLivePosts();
            return View();
        }
        public ActionResult SalesOrderList(string livepageId)
        {
            if (livepageId == null)
            {
                return RedirectToAction("Index");
            }
            ViewData["livepageId"] = livepageId;
            var salesOrderVM = SalesOrderListService.ListSalesOrders(livepageId);
            return View(salesOrderVM);
        }
        public ActionResult CommentsOrderList(int liveId)
        {
            LivePostsRepository livePost_repo = new LivePostsRepository();
            ViewData["LivePost"] = livePost_repo.GetLivePost(liveId);
            ViewBag.liveId = liveId;
            OrderRepositories order_repo = new OrderRepositories();
            List<CommentOrderLIstViewModel> orders = order_repo.GetOrders(liveId);
            ViewData.Model = orders;
            return View();
        }
        public ActionResult ROIOrderList(int liveId)
        {
            LivePostsRepository livePost_repo = new LivePostsRepository();
            ViewData.Model = livePost_repo.GetLivePost(liveId);

            var SaleOrder = livePost_repo.SaleOrder(liveId);
            ViewData["SaleOrder"] = SaleOrder;
            return View();
        }
        public ActionResult LineList()
        {
            string userId = User.Identity.GetUserId();
            int[] storeManagerIDs=CampaignService.GetStoreManagerIDs(userId);           
            ViewData.Model = CampaignService.GetAllCampaigns(storeManagerIDs);
            return View();
        }
        public ActionResult GroupOrderList(int campaignID)
        {
            ViewBag.campaignID = campaignID;            
            GroupOrderService groupOrderService = new GroupOrderService();           
            var groupOrders = groupOrderService.SelectGroupOrders(campaignID);
            CampaignService campaignService = new CampaignService();
            CampaignViewModel cvm = campaignService.GetCampaign(campaignID);
            ViewBag.title = cvm.Title;
            ViewBag.productName = cvm.ProductName;
            ViewBag.detail = cvm.Detail;
            ViewBag.productGroup = cvm.ProductGroup;           
            ViewData.Model = groupOrders;            
            
            
            return View();
        }
        public ActionResult GroupOrderDetailList(int GroupOrderID,int campaignID)
        {
            ViewBag.campaignID = campaignID;
            ViewBag.GroupOrderID = GroupOrderID;
            var GOdetailService = new GroupOrderDetailService();
            ViewData.Model=GOdetailService.GetDetailByGroupOrderID(GroupOrderID);
            return View();
        }
    }
}

PlusOneBuy/FBPlusOneBuy/Views/Shared/Main_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PlusOneBuy</title>
    <link rel="Shortcut Icon" type="image/x-icon" href="https://i1.wp.com/www.91app.com/wp-content/uploads/91app-logo-general-image.jpg?fit=1200%2C1200&ssl=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="~/Assets/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.css" >
    @RenderSection("TopCss", false)
    @RenderSection("TopJs", false)
</head>
<body>
    <div class="container-fluid" style="height: 100%;">



        <div class="row header">
            <img src="/Assets/images/91app_developer.png" />
            <div class="col text-right m-3">
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("Logoff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <label>@User.Identity.Name</label>
                        <a style="text-decoration: none;" href="javascript:document.getElementById('logoutForm').submit()">登出<i class="fas fa-sign-out-alt ml-2"></i></a>
                    }
                }
            </div>
        </div>
        <div class="row" style="height:90%;">
            <div class="col-2 nav_">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("FanPageName","Setting")" role="button">
                            <i class="fas fa-tasks mr-3"></i>設定活動
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("Index","Report")" role="button">
                            <i class="fas fa-file mr-3"></i>查詢活動
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("BindAccount","Account")" role="button">
                            <i class="fas fa-cogs mr-2"></i>綁定帳號
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col content">
                @RenderBody()
            </div>
        </div>
    </div>
   
    <script src="~/Assets/js/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js"></script>
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@

    @RenderSection("scripts", required: false)
    @RenderSection("EndJS", false)
    <script>
        $('#logout').click(function () {
            $.ajax({
            type: "POST",
            url: '@Url.Action("LogOff","Account")'
        })
        })

    </script>
</body>

</html>

PlusOneBuy/FBPlusOneBuy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PlusOneBuy</title>
    <link rel="Shortcut Icon" type="image/x-icon" href="https://i1.wp.com/www.91app.com/wp-content/uploads/91app-logo-general-image.jpg?fit=1200%2C1200&ssl=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="~/Assets/css/styles.css" rel="stylesheet" />
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    @RenderSection("TopCss", false)
    @RenderSection("TopJs", false)
</head>
<body>

    @RenderBody()
    <script src="~/Assets/js/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@

    @RenderSection("scripts", required: false)
    @RenderSection("EndJS", false)
</body>

</html>